// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/y44k0v/grpc-rest-api-ykv/ent/predicate"
	"github.com/y44k0v/grpc-rest-api-ykv/ent/product"
)

// ProductUpdate is the builder for updating Product entities.
type ProductUpdate struct {
	config
	hooks    []Hook
	mutation *ProductMutation
}

// Where appends a list predicates to the ProductUpdate builder.
func (pu *ProductUpdate) Where(ps ...predicate.Product) *ProductUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetName sets the "name" field.
func (pu *ProductUpdate) SetName(s string) *ProductUpdate {
	pu.mutation.SetName(s)
	return pu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (pu *ProductUpdate) SetNillableName(s *string) *ProductUpdate {
	if s != nil {
		pu.SetName(*s)
	}
	return pu
}

// SetDescription sets the "description" field.
func (pu *ProductUpdate) SetDescription(s string) *ProductUpdate {
	pu.mutation.SetDescription(s)
	return pu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (pu *ProductUpdate) SetNillableDescription(s *string) *ProductUpdate {
	if s != nil {
		pu.SetDescription(*s)
	}
	return pu
}

// SetPrice sets the "price" field.
func (pu *ProductUpdate) SetPrice(f float64) *ProductUpdate {
	pu.mutation.ResetPrice()
	pu.mutation.SetPrice(f)
	return pu
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (pu *ProductUpdate) SetNillablePrice(f *float64) *ProductUpdate {
	if f != nil {
		pu.SetPrice(*f)
	}
	return pu
}

// AddPrice adds f to the "price" field.
func (pu *ProductUpdate) AddPrice(f float64) *ProductUpdate {
	pu.mutation.AddPrice(f)
	return pu
}

// SetPictures sets the "pictures" field.
func (pu *ProductUpdate) SetPictures(s []string) *ProductUpdate {
	pu.mutation.SetPictures(s)
	return pu
}

// AppendPictures appends s to the "pictures" field.
func (pu *ProductUpdate) AppendPictures(s []string) *ProductUpdate {
	pu.mutation.AppendPictures(s)
	return pu
}

// SetCategories sets the "categories" field.
func (pu *ProductUpdate) SetCategories(s []string) *ProductUpdate {
	pu.mutation.SetCategories(s)
	return pu
}

// AppendCategories appends s to the "categories" field.
func (pu *ProductUpdate) AppendCategories(s []string) *ProductUpdate {
	pu.mutation.AppendCategories(s)
	return pu
}

// SetQtyAvailable sets the "qty_available" field.
func (pu *ProductUpdate) SetQtyAvailable(i int32) *ProductUpdate {
	pu.mutation.ResetQtyAvailable()
	pu.mutation.SetQtyAvailable(i)
	return pu
}

// SetNillableQtyAvailable sets the "qty_available" field if the given value is not nil.
func (pu *ProductUpdate) SetNillableQtyAvailable(i *int32) *ProductUpdate {
	if i != nil {
		pu.SetQtyAvailable(*i)
	}
	return pu
}

// AddQtyAvailable adds i to the "qty_available" field.
func (pu *ProductUpdate) AddQtyAvailable(i int32) *ProductUpdate {
	pu.mutation.AddQtyAvailable(i)
	return pu
}

// SetCreatedAt sets the "created_at" field.
func (pu *ProductUpdate) SetCreatedAt(t time.Time) *ProductUpdate {
	pu.mutation.SetCreatedAt(t)
	return pu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (pu *ProductUpdate) SetNillableCreatedAt(t *time.Time) *ProductUpdate {
	if t != nil {
		pu.SetCreatedAt(*t)
	}
	return pu
}

// SetLastUpdated sets the "last_updated" field.
func (pu *ProductUpdate) SetLastUpdated(t time.Time) *ProductUpdate {
	pu.mutation.SetLastUpdated(t)
	return pu
}

// SetNillableLastUpdated sets the "last_updated" field if the given value is not nil.
func (pu *ProductUpdate) SetNillableLastUpdated(t *time.Time) *ProductUpdate {
	if t != nil {
		pu.SetLastUpdated(*t)
	}
	return pu
}

// Mutation returns the ProductMutation object of the builder.
func (pu *ProductUpdate) Mutation() *ProductMutation {
	return pu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *ProductUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, pu.sqlSave, pu.mutation, pu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pu *ProductUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *ProductUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *ProductUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pu *ProductUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(product.Table, product.Columns, sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt))
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.Name(); ok {
		_spec.SetField(product.FieldName, field.TypeString, value)
	}
	if value, ok := pu.mutation.Description(); ok {
		_spec.SetField(product.FieldDescription, field.TypeString, value)
	}
	if value, ok := pu.mutation.Price(); ok {
		_spec.SetField(product.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := pu.mutation.AddedPrice(); ok {
		_spec.AddField(product.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := pu.mutation.Pictures(); ok {
		_spec.SetField(product.FieldPictures, field.TypeJSON, value)
	}
	if value, ok := pu.mutation.AppendedPictures(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, product.FieldPictures, value)
		})
	}
	if value, ok := pu.mutation.Categories(); ok {
		_spec.SetField(product.FieldCategories, field.TypeJSON, value)
	}
	if value, ok := pu.mutation.AppendedCategories(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, product.FieldCategories, value)
		})
	}
	if value, ok := pu.mutation.QtyAvailable(); ok {
		_spec.SetField(product.FieldQtyAvailable, field.TypeInt32, value)
	}
	if value, ok := pu.mutation.AddedQtyAvailable(); ok {
		_spec.AddField(product.FieldQtyAvailable, field.TypeInt32, value)
	}
	if value, ok := pu.mutation.CreatedAt(); ok {
		_spec.SetField(product.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := pu.mutation.LastUpdated(); ok {
		_spec.SetField(product.FieldLastUpdated, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{product.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pu.mutation.done = true
	return n, nil
}

// ProductUpdateOne is the builder for updating a single Product entity.
type ProductUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProductMutation
}

// SetName sets the "name" field.
func (puo *ProductUpdateOne) SetName(s string) *ProductUpdateOne {
	puo.mutation.SetName(s)
	return puo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillableName(s *string) *ProductUpdateOne {
	if s != nil {
		puo.SetName(*s)
	}
	return puo
}

// SetDescription sets the "description" field.
func (puo *ProductUpdateOne) SetDescription(s string) *ProductUpdateOne {
	puo.mutation.SetDescription(s)
	return puo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillableDescription(s *string) *ProductUpdateOne {
	if s != nil {
		puo.SetDescription(*s)
	}
	return puo
}

// SetPrice sets the "price" field.
func (puo *ProductUpdateOne) SetPrice(f float64) *ProductUpdateOne {
	puo.mutation.ResetPrice()
	puo.mutation.SetPrice(f)
	return puo
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillablePrice(f *float64) *ProductUpdateOne {
	if f != nil {
		puo.SetPrice(*f)
	}
	return puo
}

// AddPrice adds f to the "price" field.
func (puo *ProductUpdateOne) AddPrice(f float64) *ProductUpdateOne {
	puo.mutation.AddPrice(f)
	return puo
}

// SetPictures sets the "pictures" field.
func (puo *ProductUpdateOne) SetPictures(s []string) *ProductUpdateOne {
	puo.mutation.SetPictures(s)
	return puo
}

// AppendPictures appends s to the "pictures" field.
func (puo *ProductUpdateOne) AppendPictures(s []string) *ProductUpdateOne {
	puo.mutation.AppendPictures(s)
	return puo
}

// SetCategories sets the "categories" field.
func (puo *ProductUpdateOne) SetCategories(s []string) *ProductUpdateOne {
	puo.mutation.SetCategories(s)
	return puo
}

// AppendCategories appends s to the "categories" field.
func (puo *ProductUpdateOne) AppendCategories(s []string) *ProductUpdateOne {
	puo.mutation.AppendCategories(s)
	return puo
}

// SetQtyAvailable sets the "qty_available" field.
func (puo *ProductUpdateOne) SetQtyAvailable(i int32) *ProductUpdateOne {
	puo.mutation.ResetQtyAvailable()
	puo.mutation.SetQtyAvailable(i)
	return puo
}

// SetNillableQtyAvailable sets the "qty_available" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillableQtyAvailable(i *int32) *ProductUpdateOne {
	if i != nil {
		puo.SetQtyAvailable(*i)
	}
	return puo
}

// AddQtyAvailable adds i to the "qty_available" field.
func (puo *ProductUpdateOne) AddQtyAvailable(i int32) *ProductUpdateOne {
	puo.mutation.AddQtyAvailable(i)
	return puo
}

// SetCreatedAt sets the "created_at" field.
func (puo *ProductUpdateOne) SetCreatedAt(t time.Time) *ProductUpdateOne {
	puo.mutation.SetCreatedAt(t)
	return puo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillableCreatedAt(t *time.Time) *ProductUpdateOne {
	if t != nil {
		puo.SetCreatedAt(*t)
	}
	return puo
}

// SetLastUpdated sets the "last_updated" field.
func (puo *ProductUpdateOne) SetLastUpdated(t time.Time) *ProductUpdateOne {
	puo.mutation.SetLastUpdated(t)
	return puo
}

// SetNillableLastUpdated sets the "last_updated" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillableLastUpdated(t *time.Time) *ProductUpdateOne {
	if t != nil {
		puo.SetLastUpdated(*t)
	}
	return puo
}

// Mutation returns the ProductMutation object of the builder.
func (puo *ProductUpdateOne) Mutation() *ProductMutation {
	return puo.mutation
}

// Where appends a list predicates to the ProductUpdate builder.
func (puo *ProductUpdateOne) Where(ps ...predicate.Product) *ProductUpdateOne {
	puo.mutation.Where(ps...)
	return puo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *ProductUpdateOne) Select(field string, fields ...string) *ProductUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Product entity.
func (puo *ProductUpdateOne) Save(ctx context.Context) (*Product, error) {
	return withHooks(ctx, puo.sqlSave, puo.mutation, puo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (puo *ProductUpdateOne) SaveX(ctx context.Context) *Product {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *ProductUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *ProductUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (puo *ProductUpdateOne) sqlSave(ctx context.Context) (_node *Product, err error) {
	_spec := sqlgraph.NewUpdateSpec(product.Table, product.Columns, sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt))
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Product.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, product.FieldID)
		for _, f := range fields {
			if !product.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != product.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.Name(); ok {
		_spec.SetField(product.FieldName, field.TypeString, value)
	}
	if value, ok := puo.mutation.Description(); ok {
		_spec.SetField(product.FieldDescription, field.TypeString, value)
	}
	if value, ok := puo.mutation.Price(); ok {
		_spec.SetField(product.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := puo.mutation.AddedPrice(); ok {
		_spec.AddField(product.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := puo.mutation.Pictures(); ok {
		_spec.SetField(product.FieldPictures, field.TypeJSON, value)
	}
	if value, ok := puo.mutation.AppendedPictures(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, product.FieldPictures, value)
		})
	}
	if value, ok := puo.mutation.Categories(); ok {
		_spec.SetField(product.FieldCategories, field.TypeJSON, value)
	}
	if value, ok := puo.mutation.AppendedCategories(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, product.FieldCategories, value)
		})
	}
	if value, ok := puo.mutation.QtyAvailable(); ok {
		_spec.SetField(product.FieldQtyAvailable, field.TypeInt32, value)
	}
	if value, ok := puo.mutation.AddedQtyAvailable(); ok {
		_spec.AddField(product.FieldQtyAvailable, field.TypeInt32, value)
	}
	if value, ok := puo.mutation.CreatedAt(); ok {
		_spec.SetField(product.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := puo.mutation.LastUpdated(); ok {
		_spec.SetField(product.FieldLastUpdated, field.TypeTime, value)
	}
	_node = &Product{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{product.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	puo.mutation.done = true
	return _node, nil
}
