// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/y44k0v/grpc-rest-api-ykv/ent/order"
	"github.com/y44k0v/grpc-rest-api-ykv/ent/product"
	"github.com/y44k0v/grpc-rest-api-ykv/ent/schema"
	"github.com/y44k0v/grpc-rest-api-ykv/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	orderFields := schema.Order{}.Fields()
	_ = orderFields
	// orderDescCreatedAt is the schema descriptor for created_at field.
	orderDescCreatedAt := orderFields[0].Descriptor()
	// order.DefaultCreatedAt holds the default value on creation for the created_at field.
	order.DefaultCreatedAt = orderDescCreatedAt.Default.(func() time.Time)
	// orderDescLastUpdated is the schema descriptor for last_updated field.
	orderDescLastUpdated := orderFields[2].Descriptor()
	// order.DefaultLastUpdated holds the default value on creation for the last_updated field.
	order.DefaultLastUpdated = orderDescLastUpdated.Default.(func() time.Time)
	productFields := schema.Product{}.Fields()
	_ = productFields
	// productDescCreatedAt is the schema descriptor for created_at field.
	productDescCreatedAt := productFields[7].Descriptor()
	// product.DefaultCreatedAt holds the default value on creation for the created_at field.
	product.DefaultCreatedAt = productDescCreatedAt.Default.(func() time.Time)
	// productDescLastUpdated is the schema descriptor for last_updated field.
	productDescLastUpdated := productFields[8].Descriptor()
	// product.DefaultLastUpdated holds the default value on creation for the last_updated field.
	product.DefaultLastUpdated = productDescLastUpdated.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[4].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescLastUpdated is the schema descriptor for last_updated field.
	userDescLastUpdated := userFields[5].Descriptor()
	// user.DefaultLastUpdated holds the default value on creation for the last_updated field.
	user.DefaultLastUpdated = userDescLastUpdated.Default.(func() time.Time)
}
